### ISSUE TITLE
not working at v56

### ISSUE THREAD

**Issue by blueman5** [xAstroBoy/lc-hax#13]
`Already up to date.
  Determining projects to restore...
  Restored C:\Users\tania\Downloads\lc-hax\lc-hax\lc-hax.csproj (in 5.3 sec).
C:\Users\tania\Downloads\lc-hax\lc-hax\Scripts\Helpers\Players.cs(301,29): error CS1061: 'PlayerControllerB' does not c
ontain a definition for 'wasInElevatorLastFrame' and no accessible extension method 'wasInElevatorLastFrame' accepting
a first argument of type 'PlayerControllerB' could be found (are you missing a using directive or an assembly reference
?) [C:\Users\tania\Downloads\lc-hax\lc-hax\lc-hax.csproj]

Build FAILED.

C:\Users\tania\Downloads\lc-hax\lc-hax\Scripts\Helpers\Players.cs(301,29): error CS1061: 'PlayerControllerB' does not c
ontain a definition for 'wasInElevatorLastFrame' and no accessible extension method 'wasInElevatorLastFrame' accepting
a first argument of type 'PlayerControllerB' could be found (are you missing a using directive or an assembly reference
?) [C:\Users\tania\Downloads\lc-hax\lc-hax\lc-hax.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:17.09
Unhandled exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\tania\Downloads\lc-hax\bin\lc-hax.dll'.
File name: 'C:\Users\tania\Downloads\lc-hax\bin\lc-hax.dll'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at Program.<<Main>$>g__Inject|0_0(String targetProcess, FileInfo assembly, String loaderNamespace, String loaderClass, String loaderMethod)
   at System.CommandLine.Handler.<>c__DisplayClass6_0`5.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
Press any key to continue . . .`

**Comment by xAstroBoy** [comment]
Yeah, because i was on vacation, now i am back.
